name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4
      with:
        fetch-depth: 0


    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        mayor_pattern: "major:"
        minor_pattern: "feat:"
        format: "${mayor}.${minor}.${patch}-prereleases${increment}"
      id: version

    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        NEW_VERSION: ${{ steps.version.outputs.version }}
      
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "New version: $NEW_VERSION!!!!!"
    
    #- name: Build Docker Image
#       run: 
#         docker build -t nelwey/docker-graphl:0.0.2 .
#         docker build -t nelwey/docker-graphl:latest .

#     - name: Push Docker Image
#       run: 
#         docker push nelwey/docker-graphl:0.0.2
#         docker push nelwey/docker-graphl:latest
        


        




        


    
    
    #- name: Build the Docker image
     # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
